### ISSUE TITLE
Datumsformat in Anzeigen sollte "localized" sein.

### ISSUE THREAD

**Issue by abirreck** [glur4k/GymStatusInfo#12]
Das sichtbare Datumsformat sollte überall lokalisiert werden.

**Comment by glur4k** [comment]
Done, zumindest sehe ich es sonst nirgends "unlocalized" ;-)

**Comment by abirreck** [comment]
Ja, aber in der Timeslots Tabelle wird die Zeit im 12h Format angezeigt :-)

**Comment by glur4k** [comment]
Hab das Datum / die Uhrzeit noch im TimeslotsTableSeeder und in der View zum bearbeiten einer Location (also beim Hinzufügen/Löschen von Timeslots einer Location) angepasst (2ad8710faf1e68e95db448462bb93261db756669).

Sonst noch wo?
