### ISSUE TITLE
E-Mail Benachrichtigung beim Erstellen einer Mannschaft

### ISSUE THREAD

**Issue by glur4k** [glur4k/GymStatusInfo#5]
Beim Erstellen einer Mannschaft muss der Name des Mannschaftsführers, dessen E-Mail und ein Passwort angegeben werden.

Wenn die Mannschaft angelegt wird, sollte eine E-Mail an die Adresse mit einem Hinweis und dem Passwort versendet werden.

Senden in der "store" Methode in "core/app/Http/Controllers/TeamsController.php".

**Comment by abirreck** [comment]
Feature-Implementierung begonnen ...

**Comment by abirreck** [comment]
Implementierung abgeschlossen.
